xiangqin/project_1/urls.py
from django.conf.urls import patterns, include, url
from project_1 import views

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'xiangqin.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^test/$', views.test, name='test'),
    url(r'^test2/$', views.test2, name='test2'),
    url(r'^test3/$', views.test3, name='test3'),
    url(r'^reqinfo/$', views.requestInfo, name='reqinfo'),
    url(r'^resinfo/$', views.resInfo, name='resinfo'),
    url(r'^detail/(?P<detail_slug>[\w\-]+)/$',views.detail,name='detail'),
    url(r'^more/$', views.more, name='more'),
)

xiangqin/xiangqin/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'xiangqin.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^project_1/', include('project_1.urls')),
)

xiangqin/project_1/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class UserProfile(models.Model) :
	name = models.CharField(max_length = 128)
	sex = models.CharField(max_length = 2)
	age = models.IntegerField(default=0)
	education = models.IntegerField (default=0)
	Occupation = models.CharField(max_length=128)
	height = models.IntegerField(default=0)
	weight = models.IntegerField(default=0)
	BJHouseholds = models.BooleanField(default = False)
	car =  models.BooleanField(default = False)
	house = models.BooleanField(default = False)
	hometown = models.CharField(max_length=1024)
	require = models.CharField(max_length=8096,blank=True)
	flag = models.BooleanField(default = False)
	WxNo = models.CharField(max_length=128,blank=True)
	img = models.ImageField(upload_to='profile_images', blank=True)
	message = models.CharField(max_length=8096,blank=True)
	QqNo = models.CharField(max_length = 128,blank=True)
	location = models.CharField(max_length = 1024,blank=True)
	Character = models.CharField(max_length = 128,blank=True)
	views = models.IntegerField(default=0)
	synopsis = models.CharField(max_length=128,blank=True)

	OpenID = models.CharField(max_length = 128, unique=True)

	def __unicode__(self) :
		return self.name

'''
class UserProfile(models.Model) :
	name = models.CharField(max_length = 128)
	sex = models.CharField(max_length = 2)
	age = models.IntegerField(default=0)
	education = models.CharField(max_length=128)
	Occupation = models.CharField(max_length=128)
	height = models.IntegerField(default=0)
	weight = models.IntegerField(default=0)
	BJHouseholds = models.BooleanField(default = False)
	car =  models.BooleanField(default = False)
	house = models.BooleanField(default = False)
	hometown = models.CharField(max_length=1024)
	require = models.CharField(max_length=8096)
	flag = models.BooleanField(default = False)
	WxNo = models.CharField(max_length=128)
	img = models.ImageField(upload_to='profile_images', blank=True)
	message = models.CharField(max_length=8096)
	QqNo = models.CharField(max_length = 128)
	location = models.CharField(max_length = 1024)
	Character = models.CharField(max_length = 128)
	views = models.IntegerField(default=0)
	synopsis = models.CharField(max_length=128)

	OpenID = models.CharField(max_length = 128, unique=True)

	def __unicode__(self) :
		return self.name
'''

'''
class Female(models.Model) :
	name = models.CharField(max_length = 128)
	sex = models.CharField(max_length = 2)
	age = models.IntegerField(default=0)
	education = models.CharField(max_length=128)
	Occupation = models.CharField(max_length=128)
	height = models.IntegerField(default=0)
	weight = models.IntegerField(default=0)
	BJHouseholds = models.BooleanField(default = False)
	car =  models.BooleanField(default = False)
	house = models.BooleanField(default = False)
	hometown = models.CharField(max_length=1024)
	require = models.CharField(max_length=8096)
	flag = models.BooleanField(default = False)
	WxNo = models.CharField(max_length=128)
	img = models.ImageField(upload_to='Female', blank=True)
	message = models.CharField(max_length=8096)
	QqNo = models.CharField(max_length = 128)
	location = models.CharField(max_length = 1024)
	Character = models.CharField(max_length = 128)
	views = models.IntegerField(default=0)
	synopsis = models.CharField(max_length=128)

	def __unicode__(self) :
		return self.name

class Man(models.Model) :
	name = models.CharField(max_length = 128)
	sex = models.CharField(max_length = 2)
	age = models.IntegerField(default=0)
	education = models.CharField(max_length=128)
	Occupation = models.CharField(max_length=128)
	height = models.IntegerField(default=0)
	weight = models.IntegerField(default=0)
	BJHouseholds = models.BooleanField(default = False)
	car =  models.BooleanField(default = False)
	house = models.BooleanField(default = False)
	hometown = models.CharField(max_length=1024)
	require = models.CharField(max_length=8096)
	flag = models.BooleanField(default = False)
	WxNo = models.CharField(max_length=128)
	img = models.ImageField(upload_to='man', blank=True)
	message = models.CharField(max_length=8096)
	QqNo = models.CharField(max_length = 128)
	location = models.CharField(max_length = 1024)
	Character = models.CharField(max_length = 128)
	views = models.IntegerField(default=0)
	synopsis = models.CharField(max_length=128)

	def __unicode__(self) :
		return self.name
'''

xiangqin/project_1/views.py
# coding:utf-8
from django.shortcuts import render
from django.template import RequestContext
from django.shortcuts import render_to_response
from django.http import HttpResponse,HttpResponseRedirect
from project_1.forms import Register,RequestForm
from project_1.models import UserProfile
from django.core.urlresolvers import reverse
from django.shortcuts import redirect
from django.core import serializers
from urllib import urlencode,unquote,quote

import json

#from django.utils import simplejson
    # sudo apt-get install python-simplejson
    # import error

#from project_1.models import Female
#from project_1.models import Man


# Create your views here.

def test(request) :
	context_dict = {}
	return render(request, 'project_1/test.html')

def test2(request):
	context_dict={}
	try:
		'''
		female = Female.objects.all()
		man = Man.objects.all()
		context_dict['female'] = female 
		context_dict['man'] = man 
		'''

		userProfile = UserProfile.objects.all()
		context_dict['userProfile'] = userProfile
	except UserProfile.DoesNotExist:
		pass 

	return render_to_response( 'project_1/test2.html',context_dict)
'''
def test3(request) :
	if request.method == 'POST' :
		form = Register(request.POST)
		if form.is_valid() :
			form.save()
			print form.cleaned_data
			return render(request, 'project_1/test.html')
		else :
			print form.errors
	else :
		form = Register()
	return render(request, 'project_1/test3.html', {'form' : form})
'''

def test3(request) :
	if request.method == 'POST' :
		userform = Register(request.POST)
		#print request.POST
		if userform.is_valid() :
			userform.save()
#------------------------------------------------------------------------------
			request.session['OpenID'] = request.POST.get('OpenID')
#------------------------------------------------------------------------------

			#print userform.cleaned_data
			#return render(request,'project_1/test.html')
			#return HttpResponseRedirect('project_1/requestInfo.html')
			#return render_to_response('project_1/requestInfo.html')
			#return render(request,'project_1/requestInfo.html')
			#return HttpResponseRedirect()
			return render(request,'project_1/requestInfo.html',{'requestform':RequestForm()})
		else :
			print userform.errors
	else :
		userform = Register()
	return render(request,'project_1/test3.html', {'userform' : userform})


Mes = "%s;%s;%s;%s;%s;%s;%s;%s"

def requestInfo(request):
    if request.method == 'POST' :
        requestform = RequestForm(request.POST)
        if requestform.is_valid():
            #get infomation from POST
            sex = request.POST.get('sex',False)
            ages = request.POST.get('ages',False)
            height = request.POST.get('height',False)
            weight = request.POST.get('weight',False)
            hometown = request.POST.get('hometown',False)
            education = request.POST.get('education',False)
            Occupation = request.POST.get('Occupation',False)
            aim = request.POST.get('aim',False)
            #
            #info = sex + '_'+ages + '_'+height+'_'+weight+'_'+hometown+'_'+education+'_'+Occupation+'_'+aim
            #print requestform
            info = Mes % (sex, ages,height,weight,hometown,education,Occupation,aim)
            #print info 
            #return 
            UserProfile.objects.filter(OpenID=request.session.get('OpenID',False)).update(require = info)

            #db = sqlite3.connect(user='itcast',db='db.sqlite3',password='123',charset='utf-8')
            #db = sqlite3.connect("../db.sqlite3")
            #cursor = connection.cursor()
            #cursor.execute("UPDATE UserProfile SET Require = info where OpenID='3333'")
            #cursor.execute("SELECT * FROM User")
           #transaction.commit_unless_managed()
            #db.close()
            return resInfo(request)

        else:
            print requestform.errors
    else:
        requestform = RequestForm()

    return render(request,'project_1/requestInfo.html',{'requestform':requestform})


#############################################################
AGES = {'a':(0,17),
    'b':(18,22),
    'c':(23,26),
    'd':(27,35),
    'e':(35,200), 
    }

EDUS={
    1:'初中',
    2:'高中',
    3:'大专',
    4:'大本',
    5:'硕士',
    6:'博士',
        }

def getAllObjects(P_require) :
    ''' P_require Each search condition to ';' Separated
        A total of 7 ';'  
        "sex;ages;height;weight;hometown;education;Occupation;aim"
         -- http://www.bing.com/translator/ '''

    Sel = 'SELECT * FROM project_1_UserProfile WHERE %s'
    req_list = P_require.split(';')
    res = ''
    if req_list[0] :
        res+='sex="%s" and ' % (req_list[0])
    if req_list[1] :
        res+='age >= %d and age <= %d and ' % (AGES[req_list[1]][0], AGES[req_list[1]][1])
            # can't use age in (%d,%d) 
    if req_list[2] :
        res += 'height>=%s and ' %(req_list[2])
    if req_list[3] :
        res += 'weight>=%s and ' %(req_list[3])
    if req_list[4] :
        res += 'hometown="%s" and ' % (req_list[4])
    if req_list[5] :
        res += 'education >= %s and ' % (req_list[5])
    if req_list[6] :
        res += 'Occupation="%s" and ' %(req_list[6])

    if not res.strip(): 
        # res is null or '' 
        res = '1 = 0 '
    else :
        res += '1 = 1'

    res = Sel % (res)
    ret = UserProfile.objects.raw(res)
    return ret  

def getResObjects(objs, src) :
    '''
    objs : The values found in the database contains 'require'
    xx.require : "sex;ages;height;weight;hometown;education;Occupation;aim"
    src : The values use found objs in the database 
    ret list 
    '''
    ret = []
    for obj in objs :
        req_list = obj.require.split(';')
        if req_list[0] and req_list[0] != src.sex:
            continue
        if req_list[1] and (src.age < AGES[req_list[1]][0] or src.age > AGES[req_list[1]][1]) :
            continue
        if req_list[2] and int(req_list[2]) > src.height:
            continue
        if req_list[3] and int(req_list[3]) > src.weight:
            continue
        if req_list[4] and req_list[4] != src.hometown :
            continue
        if req_list[5] and req_list[5] < int(src.education):
            continue
        if req_list[6] and  req_list[6] != src.Occupation:
            continue
        ret.append({'OpenID':obj.OpenID,
            'name':obj.name,
            'age':obj.age,
            'education': EDUS[obj.education],
            'hometown' : obj.hometown,
            'height':obj.height,
            'img':str(obj.img)});

        #ret.append(obj)
        #ret[len(ret)-1].education =  EDUS[ret[len(ret)-1].education]
    return ret 



#############################################################
def resInfo(request):
    '''
    if request.method == 'POST':
        print request.POST
    else:
        preUser = UserProfile.objects.get(OpenID=request.session.get('OpenID',False))
        getAllObjects(preUser.require)
        print "11111"
        return 
    '''
    preUser = UserProfile.objects.get(OpenID=request.session.get('OpenID',False))
    m_objects = getAllObjects(preUser.require)
    #print [x.name for x in m_objects]
    list_res = getResObjects(m_objects, preUser)
    #print list_res 
    #request.session['Objs'] = serializers.serialize('json', list_res)
    request.session['Objs'] = json.dumps(list_res)
    print request.session.get('Objs',False)

    request.session['Objs_n'] = 10;
    return render(request,'project_1/resInfo.html',{'list_res':list_res[:10]})
    

"""
'''
        reqInfo = preUser.require
        print reqInfo
        
        req_list = reqInfo.split(';')
        sex = req_list[0]
        ages = req_list[1] 
        height = req_list[2]
        weight = req_list[3]
        hometown = req_list[4]
        education = req_list[5]
        Occupation = req_list[6]
        aim = req_list[7]
        '''
        '''
        list_res = []
        res_object = UserProfile.objects.filter(sex=sex)
        for res in res_object:
            reqInfo_other = res.require

            req_otherlist = reqInfo_other.split(';')

            oth_sex = req_otherlist[0]
            oth_ages = req_otherlist[1]
            oth_height = req_otherlist[2]
            oth_weight = req_otherlist[3]
            oth_hometown = req_otherlist[4]
            oth_education = req_otherlist[5]
            oth_Occupation = req_otherlist[6]
            oth_aim = req_otherlist[7]

            if oth_sex == preUser.sex:
                list_res.append(res)
    return render(request,'project_1/resInfo.html',{'list_res':list_res})
    '''
"""

def detail(request,detail_slug):
    context_dict = {}
    try:
        she_he = UserProfile.objects.get(OpenID=detail_slug)
        context_dict['she_he'] = she_he
    except UserProfile.DoseNotExist:
        pass
    return render(request,'project_1/detail.html',context_dict)



def more(request) :
    list_res = json.loads(request.session.get('Objs', False))
    n = int(request.session.get('Objs_n',False))
    #print list_res
    #print type(list_res)
    #print [x for x in list_res]
    ret = []
    
    if len(list_res) > n :
        ret = list_res[n:n+10]
        request.session['Objs_n'] = n+10 
    
    return HttpResponse(json.dumps(ret), content_type="application/json")
    #return HttpResponse(json.dumps( {'id': 1, 'name': "虫子"}).decode(),content_type="application/json")

xiangqin/templates/project_1/detail.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="zh-CN">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="">
        <meta name="author" content="">
        <link rel="icon" href="../../favicon.ico">
        <title>meethere缘分来了</title>
        <link href="//cdn.bootcss.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet">
        <link href="navbar-static-top.css" rel="stylesheet">
        <script src="../../assets/js/ie-emulation-modes-warning.js"></script>
        <style>
            h1 {text-align:center;}
            p.font{
              font-size: 20px;
              font-family: "Courier New", Courier, monospace;
              background-image: url(/static/img/abj2.jpg);
              background-size: cover;
            }
            div.font{
              font-size: 20px;
            }
            #wrap {
              min-height: 100%;
              background-color: none;
              height: auto !important;
              margin: 0px auto -309px;
              padding: 0px 0px 309px;
            }
           body
            {
                background-image: url(/static/img/abj2.jpg);
              
                background-size: cover;
                background-position: center;
            }
        </style>
    </head>
    <body>
    <div class="container">   
            <h1><b style="color:#FF0000">meethere缘分来了</b></h1>
                  <hr class="featurette-divider">
                        <form class="form-signin span8" id="detail" method="post" action="">
                                  {% csrf_token %}
                              <div class="row featurette">
                                    <div class="col-xs-12">
                                              <img class="featurette-image img-responsive center-block" data-src="holder.js/500x500/auto" alt="Generic placeholder image" src="/static/img/{{ she_he.img }}" >
                                    </div>
                             </div>
                            <div class="row featurette">
                                                <h2 class="featurette-heading">Oh yeah, it's that good. 
                                                          <span class="text-muted">See for yourself.</span></h2>
                                                <p class="lead" >
                                                            <div class ="row featurette">
                                                                        <div class="col-xs-6">
                                                                                  <h3>姓 名: </h3></div>
                                                                        <div class="col-xs-5 ">
                                                                                    <h3>{{ she_he.name }}<h3>
                                                                        </div>
                                                            </div>
                                                            <div class ="row featurette">
                                                                          <div class="col-xs-6">
                                                                                    <h3>年 龄: </h3></div>
                                                                          <div class="col-xs-5">
                                                                                  <h3>{{ she_he.age }}</h3>
                                                                          </div>
                                                            </div>
                                                            <div class ="row featurette">
                                                                          <div class="col-xs-6">
                                                                                    <h3>学 历: </h3></div>
                                                                          <div class="col-xs-5">
                                                                                    <h3>{{ she_he.education }}</h3>
                                                                          </div>
                                                            </div>
                                                            <div class ="row featurette">
                                                                            <div class="col-xs-6">
                                                                                      <h3>身 高: </h3></div>
                                                                            <div class="col-xs-5">
                                                                                        <h3> {{ she_he.height }}</h3>
                                                                            </div>
                                                            </div>
                                                           <div class ="row featurette">
                                                                            <div class="col-xs-6">
                                                                                      <h3>住 宅: </h3></div>
                                                                            <div class="col-xs-5">
                                                                                        <h3> {{ she_he.hometown }}</h3>
                                                                             </div>
                                                            </div>
                                                            <div class ="row featurette">
                                                                      <div class="col-xs-12"><h3>个人信息:</h3></div>
                                                              </div>
                                                              <div class ="row featurette">
                                                                      <p class="navbar-text  font col-xs-12" >
                                                                            个人，或者称个体，一般指一个人或是一个群体中的特定的主体。一个人、个体（跟“集体”相对）个人利益服从集体利益，集体领导同个人负责相结合。自称我（在正式场合发表意见时...
                                                                      </p>
                                                            </div>
                                                  </p>
                              </div>
                          </form>
                   </div>  
        <div style="text-align:center;">
               <button type="button" class="btn btn-primary">拒绝</button>
               <button type="button" class="btn btn-success">确定</button>
        </div>

        <script src="//cdn.bootcss.com/jquery/1.11.3/jquery.min.js"></script>
        <script src="//cdn.bootcss.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
        <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>
        </body>
</html>

xiangqin/templates/project_1/requestInfo.html
<!DOCTYPE html>
 {% load staticfiles %}
<html lang="zh-CN">
<head>
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8"/>
    <title>meethere缘分来了</title>
    <style type="text/css">

    </style>
    <script type="text/javascript" src="/static/js/jquery-2.0.3.min.js"></script>
    <script type="text/javascript">
        $(document).ready(function(){

        })
    </script>
<link href="//cdn.bootcss.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet">
<link href="navbar-static-top.css" rel="stylesheet">
<script src="../../assets/js/ie-emulation-modes-warning.js"></script>
<style>
#sub{width:100px;height:35px;line-height:35px;background:transparent url(/static/img/bg2.jpg) no-repeat;border:none;}
#center{text-align:center;}
body{
              background-image: url(/static/img/abj2.jpg);
              background-size:cover;
              background-color: #FFB5B5; 
         }

</style>
</head>
<body>
<div class="container">
   <a href="/project_1/test/"><h1><b style= "color : #FF0033">meethere缘分来了</b></h1></a>
    <hr class="featurette-divider">

    <form class="form-signin span8" id="ReruestInfo" method="post" action="/project_1/reqinfo/">
        {% csrf_token %}
        {% if requestform %}
        {% for field in requestform %}
        {{ field.errors }}<br/>
        {{ field.label }}
        {{ field }}
        <br />
        {% endfor %}

        {% else %}
        <strong>requestfrom error </strong>
        {% endif %}
        <div>
        <br />
        <br />
        <input type="submit" value="submit" id="sub"/>
        </div>
    </form>
    <br />
    <br />

</div>

<div id="center">
<p >本网站meethere缘分来了<a href="/project_1/test/">www.meethere.com</a>版权所有。</p>
</div>
<script src="//cdn.bootcss.com/jquery/1.11.3/jquery.min.js"></script>
<script src="//cdn.bootcss.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
<script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>
</body>
</html>

xiangqin/templates/project_1/test.html
<!DOCTYPE html>
{% load staticfiles %} <!-- load static file path -->
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8"/>
	<title>test</title>
	<link rel="stylesheet" type="text/css" href="/static/css/test1.css" />
	<link rel="stylesheet" type="text/css" href="{% static "css/test2.css" %}" />
	<script type="text/javascript" src="/static/js/test.js"></script>
</head>
<body>
	<h1>RUN ok</h1>

	<a href="http://www.bilibili.com"><img src="/static/img/1.jpg" /></a>
	<br />
	or
	<a href="http://www.bilibili.com"><img src="{% static "img/1.jpg" %}"></a>
	<br />
	<p class="font1">test css</p>

	<input type="text" id="text" />
	<input type="button" onclick="tesing()" value="click">
</body>
</html>

xiangqin/templates/project_1/test2.html
<!DOCTYPE html>
{% load staticfiles %} <!-- load static file path -->
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8"/>
	<title>test2</title>
</head>
<body>
	<h1>data</h1>
	<!-- 
	{% if female %}
	<ul>
		{% for obj in female %}
		<li>{{  obj.name }}: age {{ obj.age }}  education {{ obj.education }}</li>
		{% endfor %}
	</ul>
	{% else %}
		<strong>female error </strong>
	{% endif %}

	{% if man %}
	<ul>
		{% for obj in man %}
		<li>{{  obj.name }}: Occupation {{ obj.Occupation }} Height {{ obj.height }}</li>
		{% endfor %}
	</ul>
	{% else %}
		<strong>man error </strong>
	{% endif %}
	-->


	{% if userProfile %}
	<ul>
		{% for obj in userProfile %}
		<li>{{  obj.name }}: Occupation {{ obj.Occupation }} Height {{ obj.height }}</li>
		{% endfor %}
	</ul>
	{% else %}
		<strong>userProfile error </strong>
	{% endif %}

</body>
</html>

xiangqin/templates/project_1/test3.html
<!DOCTYPE html>
 {% load staticfiles %}
<html lang="zh-CN">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8"/>
	<title>MeetHere缘分来了</title>
	<style type="text/css">
		.register{
			color:#E15F63;
			font-size:15px;
		}
		.BB{
			color:#FF0033;
			font-size:15px;
		}
	</style>
	<script type="text/javascript" src="/static/js/jquery-2.0.3.min.js"></script>
	<script type="text/javascript">
		$(document).ready(function(){
			$('#id_name').click(function(){
				//alert("ok");
				//$('.register').css("color" ,"#FF0033");
				//$("#id_name").prev().removeClass().addClass("BB")
			})
		})
	</script>
 <link href="//cdn.bootcss.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet">
 <link href="navbar-static-top.css" rel="stylesheet">
 <script src="../../assets/js/ie-emulation-modes-warning.js"></script>
 <style>
#sub{width:100px;height:35px;line-height:35px;background:transparent url(/static/img/bg2.jpg) no-repeat;border:none;}
#center{text-align:center;}
body{
              background-image: url(/static/img/abj2.jpg);
              background-size:cover;
              background-color: #FFB5B5; 
         }

</style>	
</head>

<body> 
<div class="container">
   <a href="/project_1/test/"><h1><b style= "color : #FF0033">meethere缘分来了</b></h1></a>
     <hr class="featurette-divider">

	<script type="text/javascript" src="/static/js/test.js"></script> 
	<form class="form-horizantal" id="Register" method="post" action="">

		{% csrf_token %}
		{% for hidden in userform.hidden_fields %}
			{{ hidden }}
		{% endfor %}
		 
		{% for field in userform.visible_fields %}
            		{{ field.errors }}<br/>
            		<div class="col-xs-3">
            		{{ field.label }}
            		</div>
            		{{ field }}	
            		<br />
        		{% endfor %}
        		
        		<div>
        		<br />
        		<br />
        		<input type="submit"  value="下一步" id="sub"> 
        		<!-- <a href="/project_1/test/"><input type="button" id="sub" value="下一步" /></a> -->
        		<br />
        		</div>
 	      		
              </form>
              <br />
              <br />
  
</div>

	<!--
	<form id="register" method="post" action="">

		{% csrf_token %}
		{% for hidden in form.hidden_fields %}
			{{ hidden }}
		{% endfor %}
		 
		{% for field in userform.visible_fields %}
    		{{ field.errors }}<br/>
    		{{ field.label }}
    		{{ field }}
    		<br />
		{% endfor %}

		<!-- {% csrf_token %}
		{{ form.as_p }}
		<input type="submit" value="Submit" />
		-->
		<!-- 
		{% for field in form %}
	            	{{ field.errors }}<br/>
	            	<span class="register">
	            	{{ field.help_text}}
	            	</span>
	            	{{ field }}  
	            	{% endfor %}
	            	- ->

		<input type="submit" value="Submit" />
	</form> -->

<div id="center">
<p >本网站meethere缘分来了<a href="/project_1/test/">www.meethere.com</a>版权所有。</p>
</div>
<script src="//cdn.bootcss.com/jquery/1.11.3/jquery.min.js"></script>
<script src="//cdn.bootcss.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
<script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>
</body>
</html>